export const WORD_BANK = {
  animais: [
    'pato','cachorro','gato','cavalo','vaca','boi','porco','galinha','galo','ovelha','cabra','coelho','rato','hamster','tartaruga','jabuti','cobra','lagarto','jacare','crocodilo','sapo','ra','peixe','tubarao','baleia','golfinho','polvo','lula','caranguejo','lagosta','camarao','agua-viva','estrela-do-mar','pinguim','foca','leao-marinho','urso','urso-polar','leao','tigre','onca','leopardo','guepardo','lobo','raposa','hiena','elefante','girafa','zebra','rinoceronte','hipopotamo','macaco','gorila','chimpanze','orangotango','canguru','coala','panda','tamandua','tatu','capivara','anta','veado','alce','bufalo','camelo','dromedario','lhama','alpaca','esquilo','morcego','ouriço','lontra','castor','guaxinim','preguica','suricato','aguia','gaviao','falcao','coruja','papagaio','arara','tucano','canario','pombo','pardal','beija-flor','avestruz','ema','pavao','cisne','ganso','pelicano','flamingo','urubu','corvo','formiga','abelha','borboleta','aranha'
  ],
  frutas: [
    'uva','banana','maca','pera','laranja','limao','tangerina','mexerica','abacaxi','mamao','manga','melancia','melao','morango','amora','framboesa','mirtilo','cereja','acerola','goiaba','maracuja','kiwi','coco','abacate','caqui','figo','roma','pessego','nectarina','ameixa','damasco','jaca','carambola','pitanga','jabuticaba','graviola','caju','umbu','cajá','cupuaçu','acai','guarana','pitaya','lichia','mangostao','rambutao','tamarindo','seriguela','nespera','physalis','fruta-do-conde','atemóia','sapoti','jenipapo','pequi','bacuri','buriti','murici','araticum','cambuci','grumixama','uvaia','cagaita','mamao-papaia','lima','cidra','pomelo','toranja','kumquat','cranberry','groselha','amora-branca','amora-preta','framboesa-vermelha','framboesa-preta','melancia-amarela','melao-cantalupo','melao-galia','melao-amarelo','banana-prata','banana-nanica','banana-da-terra','banana-maca','maca-verde','maca-gala','maca-fuji','pera-williams','pera-portuguesa','uva-verde','uva-roxa','uva-rubi','manga-palmer','manga-tommy','manga-rosa','goiaba-vermelha','goiaba-branca','maracuja-doce','maracuja-azedo','abacaxi-perola','abacaxi-havai','coco-verde','coco-seco','pinha'
  ],
  comidas: [
    'arroz','feijao','macarrao','lasanha','pizza','hamburguer','cachorro-quente','sanduiche','pastel','coxinha','empada','esfiha','quibe','pao','bolo','torta','pudim','brigadeiro','beijinho','sorvete','chocolate','biscoito','bolacha','pipoca','pamonha','curau','canjica','tapioca','cuscuz','farofa','feijoada','churrasco','strogonoff','risoto','nhoque','panqueca','omelete','ovo-frito','batata-frita','pure','salada','sopa','caldo','moqueca','acaraje','vatapa','baiao-de-dois','tropeiro','virado','polenta','mandioca','aipim','torresmo','linguica','salsicha','bife','frango-assado','frango-frito','peixe-frito','sushi','sashimi','temaki','yakisoba','ramen','taco','burrito','nachos','guacamole','paella','croissant','waffle','donut','churros','crepe','brownie','cupcake','mousse','gelatina','doce-de-leite','goiabada','pacoca','pe-de-moleque','cocada','rapadura','queijo','presunto','salame','mortadela','requeijao','iogurte','granola','cereal','aveia','pao-de-queijo','rosquinha','sonho','rabanada','quindim','bombom','trufa','marmelada','hamburguer-artesanal'
  ],
  objetos: [
    'cadeira','mesa','sofa','cama','travesseiro','colchao','armario','guarda-roupa','gaveta','espelho','lampada','abajur','ventilador','televisao','controle','celular','telefone','computador','notebook','teclado','mouse','monitor','camera','relogio','oculos','chave','cadeado','mochila','bolsa','carteira','garrafa','copo','caneca','prato','tigela','garfo','faca','colher','panela','frigideira','chaleira','liquidificador','batedeira','micro-ondas','geladeira','fogao','forno','vassoura','rodo','balde','esponja','toalha','sabonete','escova','pente','tesoura','agulha','linha','martelo','prego','parafuso','chave-de-fenda','alicate','furadeira','serrote','pa','enxada','mangueira','escada','corda','corrente','capacete','bola','boneca','carrinho','livro','caderno','lapis','caneta','borracha','regua','moeda','nota','cartao','guarda-chuva','oculos-de-sol','chapeu','bone','sapato','chinelo','tenis','camisa','calca','meia','cinto','anel','brinco','colar','pulseira','violao','fone'
  ]
};

export const CATEGORY_LABELS = {
  animais: 'Animal',
  frutas: 'Fruta',
  comidas: 'Comida',
  objetos: 'Objeto'
};
